### PR TITLE
:heavy_plus_sign: Replace dependencies with open-api-dependencies

### PR DESCRIPTION
**Pull request by stevenbal**
taiga issue: https://taiga.maykinmedia.nl/project/maykin-intranet/issue/739
closes: https://github.com/maykinmedia/objects-api/issues/386

### CODE REVIEW

**Comment by stevenbal** [comment]
@joeribekker the kanalen page does not extend another template in the latest version of `notifications-api-common`, leaving out styling:
image

Before I try to fix this in the library, do we want these kanalen pages to begin with? Because for Open Zaak we switched to links to github at some point: https://github.com/VNG-Realisatie/besluiten-api/blob/develop/src/notificaties.md

**Comment by joeribekker** [comment]
Good call Steven but then we need to add those pages to GitHub or docs

**Comment by annashamray** [comment]
As discussed on Slack let's:
* wait for https://github.com/maykinmedia/objects-api/pull/362 to be merged
* update django in open-api-dependencies to 4.2 and then introduce it

**Comment by stevenbal** [comment]
@annashamray this PR is ready for review again

**Pull request merged**
